language: python

python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - pip install tox

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)

cache:
  - pip

notifications:
  email: false
